name: Generate Space Shooter

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Space Shooter
        uses: czl9707/gh-space-shooter@main
        with:
          github_user_name: jibin7jose
          outputs: github-contribution-grid-space-shooter.gif
        
      - name: Commit and Push
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: .
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
