name: Generate 3D Contribution City
permissions:
  contents: write


on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D Profile
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Publish 3D City to Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: profile-3d-contrib
          build_dir: profile-3d-contrib
          commit_message: "chore: update 3d city"
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

